//src/common/enums/action-type.enum.ts

export enum ActionType {
  CREATE = 'create',
  UPDATE = 'update',
  DELETE = 'delete',
  EXPORT = 'export',
  IMPORT = 'import',
  READ = 'read',
  RESTORE = 'restore',
  FORCE_DELETE = 'force_delete',
  VERIFY = 'verify',
  APPROVE = 'approve',
  REJECT = 'reject',
  CANCEL = 'cancel',
  ASSIGN = 'assign',
  UNASSIGN = 'unassign',
  ARCHIVE = 'archive',
  UNARCHIVE = 'unarchive',
  ENABLE = 'enable',
  DISABLE = 'disable',
  PUBLISH = 'publish',
  UNPUBLISH = 'unpublish',
  LOCK = 'lock',
  UNLOCK = 'unlock',
  ACTIVATE = 'activate',
  DEACTIVATE = 'deactivate',
  SUSPEND = 'suspend',
  UNSUSPEND = 'unsuspend',
  GRANT = 'grant',
  REVOKE = 'revoke',
  OTHER = 'other',
}
